### ISSUE TITLE
Custom Glue SerDe does does not load

### ISSUE THREAD

**Issue by olivd4400** [kafbat/kafka-ui#665]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Provided sample Glue Serde https://github.com/kafbat/ui-serde-glue/tree/main
does not load and prevent UI from starting with exception below
`
Caused by: java.lang.ClassCastException: class io.kafbat.ui.serde.glue.GlueSerde cannot be cast to class io.kafbat.ui.serde.api.Serde (io.kafbat.ui.serde.glue.GlueSerde is in unnamed module of loader io.kafbat.ui.serdes.CustomSerdeLoader$ChildFirstClassloader @59496961; io.kafbat.ui.serde.api.Serde is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @179d3b25)
	at io.kafbat.ui.serdes.CustomSerdeLoader.loadAndConfigure(CustomSerdeLoader.java:46)
	at io.kafbat.ui.serdes.SerdesInitializer.loadAndInitCustomSerde(SerdesInitializer.java:265)
	at io.kafbat.ui.serdes.SerdesInitializer.createSerdeFromConfig(SerdesInitializer.java:186)
	at io.kafbat.ui.serdes.SerdesInitializer.init(SerdesInitializer.java:105)
`

### Expected behavior

Custom Serde is loaded and Kafka UI starts

### Your installation details

v1.0.0

### Steps to reproduce

1. compile Glue Serde from https://github.com/kafbat/ui-serde-glue/tree/main (with depencies)
2. copy jar in installation path
3. modify application.yml to include this custom serializer
`        - name: GlueSerde(dev)
          className: io.kafbat.ui.serde.glue.GlueSerde
          filePath: /opt/kafka-ui/glue-serde/kafkaui-glue-serde.jar
`

**Comment by Haarolean** [comment]
[`1.0.1`](https://github.com/kafbat/ui-serde-glue/releases/tag/v1.0.1) works fine for me.
Please try the latest release first to make sure you compiled it properly.

**Comment by olivd4400** [comment]
Thanks @Haarolean,

Indeed I was already using [1.0.1](https://github.com/kafbat/ui-serde-glue/releases/tag/v1.0.1) but I did rebuild it from sources and forgot the "provided" scope in pom file. With "provided" scope this work fine

`
    <dependency>
	    <groupId>io.kafbat.ui</groupId>
	    <artifactId>serde-api</artifactId>
	    <version>1.0.0</version>
	    <scope>provided</scope>
	</dependency>
`
